### ISSUE TITLE
Missing documentation for host object tracking

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/cooperative-perception-core#6]
### Type of issue

- [ ] Anomaly report (something appears to not work correctly)
- [X] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn't fall into either of the above categories)

### Descriptive summary

There is no documentation for host object tracking.

Good design documentation should include overall software architecture description, individual class and function choices, and discussion on why certain decisions were made.

The host object tracking cooperative perception subsystem needs sufficient documentation so the related software can be integrated into the bigger system.

### CARMA version where this issue was discovered

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Steps to reproduce the actual behavior

N/A

### Related work

N/A
